$$
\newcommand{\ket}[1]{\left|\,{#1}\,\right\rangle}
\newcommand{\bra}[1]{\left\langle\,{#1}\,\right|}
\newcommand{\braket}[2]{\left\langle\,{#1}\,\middle|\,{#2}\,\right\rangle}
\newcommand{\mean}[1]{\left\langle\,{#1}\,\right\rangle}
$$

# Teoría de la Información Cuántica

## Trabajo Práctico Número 1

### Ejercicio 1

#### **I.1** 

Demostrar que un operador densidad $\rho$ describe un estado puro sii $\rho^2=\rho$.

Solución:

Ida

Sea $\rho = \ket{\psi} \bra{\psi} \mapsto$ 

$\rho^2 = \rho * \rho = \ket{\psi} \bra{\psi} \ket{\psi} \bra{\psi} = \ket{\psi} \bra{\psi} = \rho$

Vuelta

Para $\rho = \Sigma_{i} p_{i}\ket{i} \bra{i} \mapsto$ 

$\rho^2 = (\Sigma_{i} p_{i}\ket{i} \bra{i})^2 = \Sigma_{i,j}p_{i}p_{i}\ket{i} \bra{i}\ket{j} \bra{j} = \Sigma_{i}p_{i}^2 \ket{i}* \delta_{ij} * \bra{j} = \Sigma_{i}p_{i}^2 \ket{i}\bra{i}$

Entonces

$\rho = \rho^2$

$\Sigma_{i} p_{i}\ket{i} \bra{i} = \Sigma_{i}p_{i}^2 \ket{i}\bra{i}$ sii $p_{i}=1 \mapsto$ estado puro 

#### **I.2** 

Mostrar que si $\rho_i$, $i=1,...,m$, son operadores densidad, entonces
$$\rho=\sum\limits_{i=1}^mp_i\rho_i\text{, }\hspace{5pt}p_i\geq0\text{, }\hspace{5pt}\sum\limits_{i=1}^mp_i=1\text{,}$$
es también un operador densidad. Esto muestra que el conjunto de operadores de densidad para un dado sistema es un conjunto convexo.

Solución:

Se puede escribir:

$\rho = \Sigma _{i} p_{i} \rho_{i} = \Sigma_{i}p_{i}(\Sigma_{j}p_{j}\ket{j} \bra{j}) = \Sigma_{j}(\Sigma_{j}p_{i}p_{j})\ket{j} \bra{j} = \Sigma_{j}q_{j}\ket{j} \bra{j}$ (operador)

Comprobamos si los $q_{j}$ están normalizados:

$\Sigma_{j}q_{j} = \Sigma_{i,j}p_{i}p_{j} = \Sigma_{i}p_{i}\Sigma_{j}p_{j} = 1$ (normalizado)

#### **I.3** 

Mostrar que $\rho=p\ket{0}\bra{0}+(1-p)\ket{1}\bra{1}$, con $p\in(1/2,1)$, puede ser escrito como $$\rho=q\ket{\alpha}\bra{\alpha}+(1-q)\ket{\beta}\bra{\beta}$$
con $q\in[1-p,p]$ arbitrario y $\ket{\alpha}$, $\ket{\beta}$ estados normalizados. Determine $\ket{\alpha}$ y $\ket{\beta}$ e interprete ambas representaciones.

Solución:

Sea $\sqrt{p_{i}}\ket{a_{i}} = \Sigma_{j}u_{j,j}\sqrt{p_{j}}\ket{j}$:


$\left.\begin{matrix}
\sqrt{p}\ket{\alpha} = u_{1,1}\sqrt{p'}\ket{0} + u_{1,2}\sqrt{1-p'}\ket{1}\\ 
\sqrt{1-p}\ket{\beta} = u_{2,1}\sqrt{p'}\ket{0} + u_{2,2}\sqrt{1-p'}\ket{1}
\end{matrix}\right\} q = \Sigma_{j,k}u_{j,k}.u_{j,k}*.\sqrt{p_{j}}\sqrt{p_{k}}.\delta_{j,k} = \Sigma|u_{j,k}|^2p_{j}$

[No sé cómo continuar]


#### **I.4** 

Mostrar que la matriz densidad más general para un qubit puede escribirse como 
$$\rho=\frac{1}{2}\left(I+\vec{r}\cdot\vec{\sigma}\right)$$
donde $\vec{r}=\left(r_x,r_y,r_z\right)$ es un vector arbitrario con $|\vec{r}|\leq 1$, y $\vec{\sigma}=(X,Y,Z)\equiv(\sigma_x,\sigma_y,\sigma_z)$ las matrices de Pauli. Determine los autovalores de $\rho$ e indiquide en qué casos $\rho$ representa un estado puro. Exprese también $\vec{r}$ en términos de $\mean{\sigma}=$ Tr $\rho\vec{\sigma}$.

Solución:

Estado puro $\Rightarrow \rho=\begin{pmatrix}
\alpha & \beta\\ 
\gamma & \delta
\end{pmatrix} ; \alpha+\delta=1$

$\left.\begin{matrix}
\delta = \frac{\delta}{2}+\frac{\delta}{2} = \frac{\delta}{2}+\frac{\delta}{2}+\frac{\alpha}{2}-\frac{\alpha}{2} = \frac{\alpha+\delta}{2}-\frac{\alpha-\delta}{2} = \frac{1}{2}-\frac{\alpha-\delta}{2}\\
\alpha = \frac{\alpha}{2}+\frac{\alpha}{2} = \frac{\alpha}{2}+\frac{\alpha}{2}+\frac{\delta}{2}-\frac{\delta}{2} = \frac{\alpha+\delta}{2}+\frac{\alpha-\delta}{2} = \frac{1}{2}+\frac{\alpha-\delta}{2}\\ 
\gamma = \beta^{*}=\beta_{r}-i\beta_{i}
\end{matrix}\right\}\rightarrow$

$\rho = \begin{pmatrix}
\frac{1}{2} + \frac{\alpha-\delta}{2} & \beta_{r}+i\beta_{i}\\ 
\beta_{r}-i\beta_{i} & \frac{1}{2} - \frac{\alpha-\delta}{2} 
\end{pmatrix} = \frac{1}{2}\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix} + \frac{\alpha - \delta}{2}\begin{pmatrix}
1 & 0\\ 
0 & -1
\end{pmatrix}+ \beta_{r}\begin{pmatrix}
0 & 1\\ 
1 & 0
\end{pmatrix} + \beta_{i}\begin{pmatrix}
0 & i\\ 
-i & 0
\end{pmatrix}$

$\rho = \frac{1}{2}\mathbb{I}+\frac{r_{x}}{2}\sigma_{x}+\frac{r_{y}}{2}\sigma_{y}+\frac{r_{z}}{2}\sigma_{z} = \frac{1}{2}(\mathbb{I}+\vec{r}\vec{\sigma})$

Entonces los autovalores quedan:

$\lambda_{1,2} = \frac{1}{2}(1\pm \sqrt{(a-c)^2+4b_{R}^2+4b_{I}^2}) = \frac{1}{2}(1\pm \left | \vec{r} \right |)$

Si es puro, $\left | \vec{r} \right | = 1$. Entonces los autovalores son $\lambda_{1}=0$ y $\lambda_{2}=1$

#### **I.5** 

Generalizar I.4 a un sistema de 2 qubits.

#### **I.6** 

Determinar todos los valores de x para los cuales

$\rho = x\ket{\phi}\bra{\phi}+(1-x) I_{d}/d$

con $\ket{\phi}$ un estado normalizado e $I_{d}$ la identidad de d x d (d = Tr($I_{d}$) es la dimensión del espacio de estados) en un operador densidad. Interpretar el estado.

Solución:

Verifico que tiene traza igual a 1 y que es semidefinido positivo.

$Tr(\rho) = Tr(x\ket{\phi}\bra{\phi}+(1-x) I_{d}/d) = xTr(\ket{\phi}\bra{\phi}) + \frac{1-x}{d}Tr(I) = x . 1 + \frac{1-x}{d}1 = 1$

[No sé cómo continuar]

### Ejercicio 2

#### **II.1** 

Para un sistema de dos qubits, escribir explı́citamente la matriz que representa a $\rho_{AB}=\ket{\Phi_{AB}}\bra{\Phi_{AB}}$ en la base computacional $\left\{\ket{00}, \ket{01}, \ket{10}, \ket{11}\right\}$ para:
$$a)\,\ket{\Phi_{AB}}=\frac{\ket{00}\pm\ket{11}}{\sqrt{2}}\text{ ,     }\,b)\,\ket{\Psi_{AB}}=\frac{\ket{00}+\ket{10}-\ket{01}-\ket{11}}{2}$$
Verificar en todos los casos que los autovalores de $\rho$ son $(1, 0, 0, 0)$.

In [1]:
! pip install qutip

In [2]:
import qutip as qt
import numpy as np

#defino las bases
ket0 = qt.basis(2,0)
ket1 = qt.basis(2,1)
ket00 = qt.tensor(ket0,ket0)
ket01 = qt.tensor(ket0,ket1)
ket10 = qt.tensor(ket1,ket0)
ket11 = qt.tensor(ket1,ket1)

In [3]:
#defino el estado
phi1 = (ket00+ket11)/np.sqrt(2)
print("\nEstado (|00>+|11>)/sqrt(2): {}".format(phi1))
#defino la matriz densidad
rho1 = qt.ket2dm(phi1)
print("Matriz densidad de (|00>+|11>)/sqrt(2): {}".format(rho1))
#calculo los autovalores
autov1, _ = rho1.eigenstates()
print('Autovalores: {}'.format(np.round(autov1,2)))


Estado (|00>+|11>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
Matriz densidad de (|00>+|11>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]
Autovalores: [0. 0. 0. 1.]


In [4]:
#defino el estado
phi2 = (ket00-ket11)/np.sqrt(2)
print("\nEstado (|00>-|11>)/sqrt(2): {}".format(phi2))
#defino la matriz densidad
rho2 = qt.ket2dm(phi2)
print("Matriz densidad de (|00>-|11>)/sqrt(2): {}".format(rho2))
#calculo los autovalores
autov2, _ = rho2.eigenstates()
print('Autovalores: {}'.format(np.round(autov2,2)))



Estado (|00>-|11>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]
Matriz densidad de (|00>-|11>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.5  0.   0.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [-0.5  0.   0.   0.5]]
Autovalores: [0. 0. 0. 1.]


In [5]:
#defino es estado
phi3 = (ket00-ket01+ket10-ket11)/2
print("\nEstado (|00>-|01>+|10>-|11>)/2: {}".format(phi3))
#defino la matriz densidad
rho3 = qt.ket2dm(phi3)
print("Matriz densidad de (|00>-|01>+|10>-|11>)/2: {}".format(rho3))
#calculo los autovalores
autov3, _ = rho3.eigenstates()
print('Autovalores: {}'.format(np.round(autov3,2)))



Estado (|00>-|01>+|10>-|11>)/2: Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]
Matriz densidad de (|00>-|01>+|10>-|11>)/2: Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]]
Autovalores: [-0. -0.  0.  1.]


#### **II.2** 

Hallar la matriz densidad reducida $\rho_A = \text{Tr}_B\,\rho_{AB}$ en todos los casos anteriores, y a partir de ella evaluar la entropı́a de entrelazamiento del estado.

In [6]:
#calculo la matriz reducida
reducida1 = rho1.ptrace(1)
#calculo auxiliar
reducida10 = rho1.ptrace(0)
print("Traca parcial de (|00>+|11>)/sqrt(2): {}".format(reducida1))
#calculo la entropía
entropia1 = qt.entropy_vn(reducida1,2)
print("Entropía de (|00>+|11>)/sqrt(2): {}".format(entropia1))

Traca parcial de (|00>+|11>)/sqrt(2): Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Entropía de (|00>+|11>)/sqrt(2): 1.0


In [7]:
#calculo la matriz reducida
reducida2 = rho2.ptrace(1)
#calculo auxiliar
reducida20 = rho2.ptrace(0)
print("Traca parcial de (|00>-|11>)/sqrt(2): {}".format(reducida2))
#calculo la entropía
entropia2 = qt.entropy_vn(reducida2,2)
print("Entropía de (|00>-|11>)/sqrt(2): {}".format(entropia2))

Traca parcial de (|00>-|11>)/sqrt(2): Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Entropía de (|00>-|11>)/sqrt(2): 1.0


In [8]:
#calculo la matriz reducida
reducida3 = rho3.ptrace(1)
#calculo auxiliar
reducida30 = rho3.ptrace(0)
print("Traca parcial de (|00>-|01>+|10>-|11>)/2: {}".format(reducida3))
#calculo la entropía
entropia3 = qt.entropy_vn(reducida3,2)
print("Entropía de (|00>-|01>+|10>-|11>)/2: {}".format(entropia3))

Traca parcial de (|00>-|01>+|10>-|11>)/2: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5 -0.5]
 [-0.5  0.5]]
Entropía de (|00>-|01>+|10>-|11>)/2: -0.0


#### **II.3** 

Hallar la descomposición de Schmidt de los estados anteriores.

Para calcular la descomposición de Schmidt debo calcular los siguiente parámetros:

$\ket{\Psi_{AB}}=\sum_{k=1}^{n_s}\sigma_k\ket{k_A}\ket{k_B}$

$\rho_A=\sum_{k=1}^{n_s}\sigma_A^2\ket{k_A}\bra{k_A}$

$\rho_B=\sum_{k=1}^{n_s}\sigma_B^2\ket{k_B}\bra{k_B}$

In [9]:
#Calculamos sigma A y Ka
sigmaA1, kA1 = reducida1.eigenstates()
#Calculamos sigma B y Kb
sigmaB1, kB1 = reducida10.eigenstates()
#Calculamos sigma K
sigmaK1 = np.sqrt(sigmaA1)
#Calculamos el número de Schmidt
n_schmidt1 = np.count_nonzero(sigmaA1)

print("(|00>+|11>)/sqrt(2):")
print("     Ket_K A: \n{} y \n{}".format(kA1[0][:], kA1[1][:]))
print("     Ket_K B: \n{} y \n{}".format(kB1[0][:], kB1[1][:]))
print("     Sigma k: {}".format(sigmaK1))
print("     Sigma A: {}".format(sigmaA1))
print("     Sigma B: {}".format(sigmaB1))
print("     Número de Schmidt: {}".format(n_schmidt1))

(|00>+|11>)/sqrt(2):
     Ket_K A: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Ket_K B: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Sigma k: [0.70710678 0.70710678]
     Sigma A: [0.5 0.5]
     Sigma B: [0.5 0.5]
     Número de Schmidt: 2


In [10]:
#Calculamos sigma A y Ka
sigmaA2, kA2 = reducida2.eigenstates()
#Calculamos sigma B y Kb
sigmaB2, kB2 = reducida20.eigenstates()
#Calculamos sigma K
sigmaK2 = np.sqrt(sigmaA2)
#Calculamos el número de Schmidt
n_schmidt2 = np.count_nonzero(sigmaA2)

print("(|00>-|11>)/sqrt(2):")
print("     Ket_K A: \n{} y \n{}".format(kA2[0][:], kA2[1][:]))
print("     Ket_K B: \n{} y \n{}".format(kB2[0][:], kB2[1][:]))
print("     Sigma k: {}".format(sigmaK2))
print("     Sigma A: {}".format(sigmaA2))
print("     Sigma B: {}".format(sigmaB2))
print("     Número de Schmidt: {}".format(n_schmidt2))

(|00>-|11>)/sqrt(2):
     Ket_K A: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Ket_K B: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Sigma k: [0.70710678 0.70710678]
     Sigma A: [0.5 0.5]
     Sigma B: [0.5 0.5]
     Número de Schmidt: 2


In [11]:
#Calculamos sigma A y Ka
sigmaA3, kA3 = reducida3.eigenstates()
#Calculamos sigma B y Kb
sigmaB3, kB3 = reducida30.eigenstates()
#Calculamos sigma K
sigmaK3 = np.sqrt(sigmaA3)
#Calculamos el número de Schmidt
n_schmidt3 = np.count_nonzero(sigmaA3)

print("(|00>-|01>+|10>-|11>)/2:")
print("     Ket_K A: \n{} y \n{}".format(kA3[0][:], kA3[1][:]))
print("     Ket_K B: \n{} y \n{}".format(kB3[0][:], kB3[1][:]))
print("     Sigma k: {}".format(sigmaK3))
print("     Sigma A: {}".format(sigmaA3))
print("     Sigma B: {}".format(sigmaB3))
print("     Número de Schmidt: {}".format(n_schmidt3))

(|00>-|01>+|10>-|11>)/2:
     Ket_K A: 
[[-0.70710678+0.j]
 [-0.70710678+0.j]] y 
[[-0.70710678+0.j]
 [ 0.70710678+0.j]]
     Ket_K B: 
[[-0.70710678+0.j]
 [ 0.70710678+0.j]] y 
[[0.70710678+0.j]
 [0.70710678+0.j]]
     Sigma k: [0. 1.]
     Sigma A: [0. 1.]
     Sigma B: [0. 1.]
     Número de Schmidt: 1


#### **II.4** 

Para $|\alpha|^2+|\beta|^2=1$, hallar la descomposición de Schmidt del estado
$$\ket{\Psi_{AB}}=\alpha\,\frac{\ket{00}+\ket{11}}{\sqrt{2}}+\beta\,\frac{\ket{01}+\ket{10}}{\sqrt{2}}$$
y a partir de ella indicar: a) cuándo el estado será separable, b) cuándo será entrelazado, y c) en qué caso el entrelazamiento será máximo.

Solución:

$\ket{+}=\frac{\ket{0}+\ket{1}}{\sqrt{2}}$ y $\ket{-}=\frac{\ket{0}-\ket{1}}{\sqrt{2}}$

$\ket{++} + \ket{--} =\ket{00}+\ket{11}$ y $\ket{++} - \ket{--} =\ket{01}+\ket{10}$

$\ket{\Psi_{AB}}=\alpha\,\frac{\ket{00}+\ket{11}}{\sqrt{2}}+\beta\,\frac{\ket{01}+\ket{10}}{\sqrt{2}} = \alpha\,\frac{\ket{++}+\ket{--}}{\sqrt{2}}+\beta\,\frac{\ket{++}-\ket{--}}{\sqrt{2}}$

$\ket{\Psi_{AB}} = \frac{\alpha + \beta}{2} \ket{++} + \frac{\alpha - \beta}{2} \ket{--}$

{$\ket{k_{a}}$} = {$\ket{+},\ket{-}$}, {$\ket{k_{b}}$} = {$\ket{+},\ket{-}$} y $\lambda_{\pm} = \frac{\alpha \pm \beta }{\sqrt{2}}$

a) Separable, para $\alpha=\pm \beta$

c) Entrelazado máximo, para ($\alpha=1$ y $\beta=0$) o ($\alpha=0$ y $\beta=1$)

b) Entrelazado, para el resto de los casos

#### **II.5** 

a) Indicar en qué se diferencian el estado de Bell $\ket{\Psi_{AB}}=\frac{\ket{01}+\ket{10}}{\sqrt{2}}$ y el estado descripto por el operador densidad
$$\rho_{AB}=\frac{1}{2}\left(\ket{01}\bra{01}+\ket{10}\bra{10}\right)$$
b) Indicar si es posible distinguirlos mediante

i) el valor medio de un observable local $O_A\otimes I_B$.

ii) el valor medio de un observable $O=O_A\otimes O_B$

In [12]:
#definimos es estado
phi_bell = (ket01+ket10)/np.sqrt(2)
print("\nEstado (|01>+|10>)/sqrt(2): {}".format(phi_bell))
#calculamos la matriz densidad
rho_bell = qt.ket2dm(phi_bell)
print("Matriz densidad de (|01>+|10>)/sqrt(2): {}".format(rho_bell))
#calculamos la matriz reducida
reducida_bell = rho_bell.ptrace(1)
print("Matriz reducida: {}".format(reducida_bell))


Estado (|01>+|10>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]
Matriz densidad de (|01>+|10>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.  0. ]]
Matriz reducida: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


In [13]:
#calculamos la matriz densidad
rho_AB = (ket01*ket01.dag()+ket10*ket10.dag())/2
print("Matriz densidad de (|01><01|+|10><10|)/2: {}".format(rho_AB))
#calculamos la matriz reducida
reducida_AB = rho_AB.ptrace(1)
print("Matriz reducida: {}".format(reducida_AB))

Matriz densidad de (|01><01|+|10><10|)/2: Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0. ]]
Matriz reducida: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


a) Vemos que la matriz densidad en ámbos casos es distinta

b)i) Sin embargo, a pesar de tener distintas matrices densidad, sus matrices reducidas locales son identicas por lo tanto no son distinguibles con ese observable

b)i) Para poder distinguirlos construyo otro observable con elementos fuera de la diagonal

In [14]:
#construyo el operador
operador = qt.tensor(qt.sigmay(), qt.sigmay())
print("Operador: {}".format(operador.get_data))
#mido el estado de Bell
medicion_bell = (rho_bell*operador).tr()
print('Matriz reducida de Bell: {}'.format(medicion_bell))
#mido el estado AB
medicion_AB = (rho_AB*operador).tr()
print('Matriz reducida de AB: {}'.format(medicion_AB))

Operador: <bound method Qobj.get_data of Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]]>
Matriz reducida de Bell: 0.9999999999999998
Matriz reducida de AB: 0.0
