$$\newcommand{\ket}[1]{\left|\,{#1}\,\right\rangle}
\newcommand{\bra}[1]{\left\langle\,{#1}\,\right|}
\newcommand{\braket}[2]{\left\langle\,{#1}\,\middle|\,{#2}\,\right\rangle}
\newcommand{\mean}[1]{\left\langle\,{#1}\,\right\rangle}$$

In [1]:
! pip install qutip

In [2]:
import qutip as qt
import numpy as np

In [3]:
ket0 = qt.basis(2,0)
ket1 = qt.basis(2,1)

ket00 = qt.tensor(ket0,ket0)
ket01 = qt.tensor(ket0,ket1)
ket10 = qt.tensor(ket1,ket0)
ket11 = qt.tensor(ket1,ket1)

**II.1** Para un sistema de dos qubits, escribir explı́citamente la matriz que representa a $\rho_{AB}=\ket{\Phi_{AB}}\bra{\Phi_{AB}}$ en la base computacional $\left\{\ket{00}, \ket{01}, \ket{10}, \ket{11}\right\}$ para:
$$a)\,\ket{\Phi_{AB}}=\frac{\ket{00}\pm\ket{11}}{\sqrt{2}}\text{ ,     }\,b)\,\ket{\Psi_{AB}}=\frac{\ket{00}+\ket{10}-\ket{01}-\ket{11}}{2}$$
Verificar en todos los casos que los autovalores de $\rho$ son $(1, 0, 0, 0)$.

In [4]:
phi1 = (ket00+ket11)/np.sqrt(2)
print("\nEstado (|00>+|11>)/sqrt(2): {}".format(phi1))
rho1 = qt.ket2dm(phi1)
print("Matriz densidad de (|00>+|11>)/sqrt(2): {}".format(rho1))
autov1, _ = rho1.eigenstates()
print('Autovalores: {}'.format(np.round(autov1,2)))


Estado (|00>+|11>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
Matriz densidad de (|00>+|11>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]
Autovalores: [0. 0. 0. 1.]


In [5]:
phi2 = (ket00-ket11)/np.sqrt(2)
print("\nEstado (|00>-|11>)/sqrt(2): {}".format(phi2))
rho2 = qt.ket2dm(phi2)
print("Matriz densidad de (|00>-|11>)/sqrt(2): {}".format(rho2))
autov2, _ = rho2.eigenstates()
print('Autovalores: {}'.format(np.round(autov2,2)))



Estado (|00>-|11>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]
Matriz densidad de (|00>-|11>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.5  0.   0.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [-0.5  0.   0.   0.5]]
Autovalores: [0. 0. 0. 1.]


In [6]:
phi3 = (ket00-ket01+ket10-ket11)/2
print("\nEstado (|00>-|01>+|10>-|11>)/2: {}".format(phi3))
rho3 = qt.ket2dm(phi3)
print("Matriz densidad de (|00>-|01>+|10>-|11>)/2: {}".format(rho3))
autov3, _ = rho3.eigenstates()
print('Autovalores: {}'.format(np.round(autov3,2)))



Estado (|00>-|01>+|10>-|11>)/2: Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]
Matriz densidad de (|00>-|01>+|10>-|11>)/2: Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]]
Autovalores: [-0. -0.  0.  1.]


**II.2** Hallar la matriz densidad reducida $\rho_A = \text{Tr}_B\,\rho_{AB}$ en todos los casos anteriores, y a partir de ella evaluar la entropı́a de entrelazamiento del estado.

In [7]:
reducida10 = rho1.ptrace(0)
reducida1 = rho1.ptrace(1)
print("Traca parcial de (|00>+|11>)/sqrt(2): {}".format(reducida1))
entropia1 = qt.entropy_vn(reducida1,2)
print("Entropía de (|00>+|11>)/sqrt(2): {}".format(entropia1))

Traca parcial de (|00>+|11>)/sqrt(2): Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Entropía de (|00>+|11>)/sqrt(2): 1.0


In [8]:
reducida20 = rho2.ptrace(0)
reducida2 = rho2.ptrace(1)
print("Traca parcial de (|00>-|11>)/sqrt(2): {}".format(reducida2))
entropia2 = qt.entropy_vn(reducida2,2)
print("Entropía de (|00>-|11>)/sqrt(2): {}".format(entropia2))

Traca parcial de (|00>-|11>)/sqrt(2): Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Entropía de (|00>-|11>)/sqrt(2): 1.0


In [9]:
reducida30 = rho3.ptrace(0)
reducida3 = rho3.ptrace(1)
print("Traca parcial de (|00>-|01>+|10>-|11>)/2: {}".format(reducida3))
entropia3 = qt.entropy_vn(reducida3,2)
print("Entropía de (|00>-|01>+|10>-|11>)/2: {}".format(entropia3))

Traca parcial de (|00>-|01>+|10>-|11>)/2: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5 -0.5]
 [-0.5  0.5]]
Entropía de (|00>-|01>+|10>-|11>)/2: -0.0


**II.3** Hallar la descomposición de Schmidt de los estados anteriores.

In [10]:
sigmaA1, kA1 = reducida1.eigenstates()
sigmaB1, kB1 = reducida10.eigenstates()
sigmaK1 = np.sqrt(sigmaA1)
n_schmidt1 = np.count_nonzero(sigmaA1)

print("(|00>+|11>)/sqrt(2):")
print("     Ket_K A: \n{} y \n{}".format(kA1[0][:], kA1[1][:]))
print("     Ket_K B: \n{} y \n{}".format(kB1[0][:], kB1[1][:]))
print("     Sigma k: {}".format(sigmaK1))
print("     Sigma A: {}".format(sigmaA1))
print("     Sigma B: {}".format(sigmaB1))
print("     Número de Schmidt: {}".format(n_schmidt1))

(|00>+|11>)/sqrt(2):
     Ket_K A: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Ket_K B: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Sigma k: [0.70710678 0.70710678]
     Sigma A: [0.5 0.5]
     Sigma B: [0.5 0.5]
     Número de Schmidt: 2


In [11]:
sigmaA2, kA2 = reducida2.eigenstates()
sigmaB2, kB2 = reducida20.eigenstates()
sigmaK2 = np.sqrt(sigmaA2)
n_schmidt2 = np.count_nonzero(sigmaA2)

print("(|00>-|11>)/sqrt(2):")
print("     Ket_K A: \n{} y \n{}".format(kA2[0][:], kA2[1][:]))
print("     Ket_K B: \n{} y \n{}".format(kB2[0][:], kB2[1][:]))
print("     Sigma k: {}".format(sigmaK2))
print("     Sigma A: {}".format(sigmaA2))
print("     Sigma B: {}".format(sigmaB2))
print("     Número de Schmidt: {}".format(n_schmidt2))

(|00>-|11>)/sqrt(2):
     Ket_K A: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Ket_K B: 
[[-1.+0.j]
 [ 0.+0.j]] y 
[[0.+0.j]
 [1.+0.j]]
     Sigma k: [0.70710678 0.70710678]
     Sigma A: [0.5 0.5]
     Sigma B: [0.5 0.5]
     Número de Schmidt: 2


In [12]:
sigmaA3, kA3 = reducida3.eigenstates()
sigmaB3, kB3 = reducida30.eigenstates()
sigmaK3 = np.sqrt(sigmaA3)
n_schmidt3 = np.count_nonzero(sigmaA3)

print("(|00>-|01>+|10>-|11>)/2:")
print("     Ket_K A: \n{} y \n{}".format(kA3[0][:], kA3[1][:]))
print("     Ket_K B: \n{} y \n{}".format(kB3[0][:], kB3[1][:]))
print("     Sigma k: {}".format(sigmaK3))
print("     Sigma A: {}".format(sigmaA3))
print("     Sigma B: {}".format(sigmaB3))
print("     Número de Schmidt: {}".format(n_schmidt3))

(|00>-|01>+|10>-|11>)/2:
     Ket_K A: 
[[-0.70710678+0.j]
 [-0.70710678+0.j]] y 
[[-0.70710678+0.j]
 [ 0.70710678+0.j]]
     Ket_K B: 
[[-0.70710678+0.j]
 [ 0.70710678+0.j]] y 
[[0.70710678+0.j]
 [0.70710678+0.j]]
     Sigma k: [0. 1.]
     Sigma A: [0. 1.]
     Sigma B: [0. 1.]
     Número de Schmidt: 1


**II.4** Para $|\alpha|^2+|\beta|^2=1$, hallar la descomposición de Schmidt del estado
$$\ket{\Psi_{AB}}=\alpha\,\frac{\ket{00}+\ket{11}}{\sqrt{2}}+\beta\,\frac{\ket{01}+\ket{10}}{\sqrt{2}}$$
y a partir de ella indicar: a) cuándo el estado será separable, b) cuándo será entrelazado, y c) en qué caso el entrelazamiento será máximo.

In [13]:
from sympy import Matrix, Trace
from sympy.abc import a,b

rho = Matrix([[a*a, b*a, b*a, a*a],[a*b, b*b, b*b, a*b],[a*b, b*b, b*b, a*b],[a*a, b*a, b*a, a*a]]) / 2
print("Matriz densidad: {}".format(rho))

Matriz densidad: Matrix([[a**2/2, a*b/2, a*b/2, a**2/2], [a*b/2, b**2/2, b**2/2, a*b/2], [a*b/2, b**2/2, b**2/2, a*b/2], [a**2/2, a*b/2, a*b/2, a**2/2]])


**II.5** a) Indicar en qué se diferencian el estado de Bell $\ket{\Psi_{AB}}=\frac{\ket{01}+\ket{10}}{\sqrt{2}}$ y el estado descripto por el operador densidad
$$\rho_{AB}=\frac{1}{2}\left(\ket{01}\bra{01}+\ket{10}\bra{10}\right)$$
b) Indicar si es posible distinguirlos mediante

i) el valor medio de un observable local $O_A\otimes I_B$.

ii) el valor medio de un observable $O=O_A\otimes O_B$

In [14]:
phi_bell = (ket01+ket10)/np.sqrt(2)
print("\nEstado (|01>+|10>)/sqrt(2): {}".format(phi_bell))
rho_bell = qt.ket2dm(phi_bell)
print("Matriz densidad de (|01>+|10>)/sqrt(2): {}".format(rho_bell))
reducida_bell = rho_bell.ptrace(1)
print("Matriz reducida: {}".format(reducida_bell))


Estado (|01>+|10>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]
Matriz densidad de (|01>+|10>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.  0. ]]
Matriz reducida: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


In [15]:
rho_AB = (ket01*ket01.dag()+ket10*ket10.dag())/2
print("Matriz densidad de (|01><01|+|10><10|)/2: {}".format(rho_AB))
reducida_AB = rho_AB.ptrace(1)
print("Matriz reducida: {}".format(reducida_AB))

Matriz densidad de (|01><01|+|10><10|)/2: Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0. ]]
Matriz reducida: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


In [16]:
operador = qt.tensor(qt.sigmay(), qt.sigmay())

medicion_bell = (rho_bell*operador).tr()
print('Matriz reducida de Bell: {}'.format(medicion_bell))

medicion_AB = (rho_AB*operador).tr()
print('Matriz reducida de AB: {}'.format(medicion_AB))

Matriz reducida de Bell: 0.9999999999999998
Matriz reducida de AB: 0.0
