In [ ]:
! pip install qutip

In [ ]:
import qutip as qt
import numpy as np
import sympy as sp
from scipy import linalg as la

$$\newcommand{\ket}[1]{\left|\,{#1}\,\right\rangle}
\newcommand{\bra}[1]{\left\langle\,{#1}\,\right|}
\newcommand{\braket}[2]{\left\langle\,{#1}\,\middle|\,{#2}\,\right\rangle}
\newcommand{\mean}[1]{\left\langle\,{#1}\,\right\rangle}$$

**II.1** Para un sistema de dos qubits, escribir explı́citamente la matriz que representa a $\rho_{AB}=\ket{\Phi_{AB}}\bra{\Phi_{AB}}$ en la base computacional $\left\{\ket{00}, \ket{01}, \ket{10}, \ket{11}\right\}$ para:
$$a)\,\ket{\Phi_{AB}}=\frac{\ket{00}\pm\ket{11}}{\sqrt{2}}\text{ ,     }\,b)\,\ket{\Psi_{AB}}=\frac{\ket{00}+\ket{10}-\ket{01}-\ket{11}}{2}$$
Verificar en todos los casos que los autovalores de $\rho$ son $(1, 0, 0, 0)$.

In [ ]:
st0 = qt.basis(2,0)
st1 = qt.basis(2,1)

st00 = qt.tensor(st0,st0)
st01 = qt.tensor(st0,st1)
st10 = qt.tensor(st1,st0)
st11 = qt.tensor(st1,st1)

In [ ]:
phi_p = (st00+st11)/np.sqrt(2)
phi_m = (st00-st11)/np.sqrt(2)
psi = (st00+st10-st01-st11)/2

rho_phi_p = qt.ket2dm(phi_p)
rho_phi_m = qt.ket2dm(phi_m)
rho_psi = qt.ket2dm(psi)

print("\nEstado (|00>+|11>)/sqrt(2): {}".format(phi_p))
print("Matriz densidad de (|00>+|11>)/sqrt(2): {}".format(rho_phi_p))
print("\nEstado (|00>-|11>)/sqrt(2): {}".format(phi_m))
print("Matriz densidad de (|00>-|11>)/sqrt(2): {}".format(rho_phi_m))
print("\nEstado (|00>+|01>+|10>+|11>)/2: {}".format(psi))
print("Matriz densidad de (|00>+|01>+|10>+|11>)/2: {}".format(rho_psi))


Estado (|00>+|11>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
Matriz densidad de (|00>+|11>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

Estado (|00>-|11>)/sqrt(2): Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]
Matriz densidad de (|00>-|11>)/sqrt(2): Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.5  0.   0.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [-0.5  0.   0.   0.5]]

Estado (|00>+|01>+|10>+|11>)/2: Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]
Matriz densidad de (|00>+|01>+|10>+|11>)/2: Quantum object: dims = [[2, 2], 

In [ ]:
avals_phi_p,_ = rho_phi_p.eigenstates()
avals_phi_m,_ = rho_phi_m.eigenstates()
avals_psi,_ = rho_psi.eigenstates()

print('Autovalores de phi_p:',np.round(avals_phi_p,3))
print('Autovalores de phi_m:',np.round(avals_phi_m,3))
print('Autovalores de psi:',np.round(avals_psi,3))

Autovalores de phi_p: [0. 0. 0. 1.]
Autovalores de phi_m: [0. 0. 0. 1.]
Autovalores de psi: [-0. -0.  0.  1.]


**II.2** Hallar la matriz densidad reducida $\rho_A = \text{Tr}_B\,\rho_{AB}$ en todos los casos anteriores, y a partir de ella evaluar la entropı́a de entrelazamiento del estado.

In [ ]:
rhoA_phi_p=rho_phi_p.ptrace(1)
rhoA_phi_m=rho_phi_m.ptrace(1)
rhoA_psi=rho_psi.ptrace(1)

print("Traca parcial de (|00>+|11>)/sqrt(2): {}".format(rhoA_phi_p))
print("Traca parcial de (|00>-|11>)/sqrt(2): {}".format(rhoA_phi_m))
print("Traca parcial de (|00>+|01>+|10>+|11>)/2: {}".format(rhoA_psi))

Traca parcial de (|00>+|11>)/sqrt(2): Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Traca parcial de (|00>-|11>)/sqrt(2): Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Traca parcial de (|00>+|01>+|10>+|11>)/2: Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5 -0.5]
 [-0.5  0.5]]


In [ ]:
E_phi_p = -(rhoA_phi_p*la.logm(rhoA_phi_p)/np.log(2)).trace()
E_phi_m = -(rhoA_phi_m*la.logm(rhoA_phi_m)/np.log(2)).trace()
E_psi = -(rhoA_psi*la.logm(rhoA_psi)/np.log(2)).trace()

print('Entropía de entrelazamiento de phi_p:',np.round(E_phi_p,3))
print('Entropía de entrelazamiento de phi_m:',np.round(E_phi_m,3))
print('Entropía de entrelazamiento de psi:',np.round(E_psi,3))

Entropía de entrelazamiento de phi_p: (1-0j)
Entropía de entrelazamiento de phi_m: (1-0j)
Entropía de entrelazamiento de psi: (-0-0j)


/usr/local/lib/python3.6/dist-packages/scipy/linalg/_matfuncs_inv_ssq.py:838: LogmNearlySingularWarning: The logm input matrix may be nearly singular.
  warnings.warn(near_singularity_msg, LogmNearlySingularWarning)


In [ ]:
sigma2A_phi_p,_ = rhoA_phi_p.eigenstates()
sigma2A_phi_m,_ = rhoA_phi_m.eigenstates()
sigma2A_psi,_ = rhoA_psi.eigenstates()

sigma2A_phi_p_nonzero = sigma2A_phi_p [sigma2A_phi_p != 0]
sigma2A_phi_m_nonzero = sigma2A_phi_m [sigma2A_phi_m != 0]
sigma2A_psi_nonzero = sigma2A_psi [sigma2A_psi != 0]

E_phi_p = -np.sum(np.square(sigma2A_phi_p_nonzero)*np.log(np.square(sigma2A_phi_p_nonzero))/np.log(2))
E_phi_m = -np.sum(np.square(sigma2A_phi_m_nonzero)*np.log(np.square(sigma2A_phi_m_nonzero))/np.log(2))
E_psi = -np.sum(np.square(sigma2A_psi_nonzero)*np.log(np.square(sigma2A_psi_nonzero))/np.log(2))

print('Entropía de entrelazamiento de phi_p:',np.round(E_phi_p,3))
print('Entropía de entrelazamiento de phi_m:',np.round(E_phi_m,3))
print('Entropía de entrelazamiento de psi:',np.round(E_psi,3))

Entropía de entrelazamiento de phi_p: 1.0
Entropía de entrelazamiento de phi_m: 1.0
Entropía de entrelazamiento de psi: -0.0


In [ ]:
E_phi_p = qt.entropy_vn(rhoA_phi_p,2)
E_phi_m = qt.entropy_vn(rhoA_phi_m,2)
E_psi = qt.entropy_vn(rhoA_psi,2)

print('Entropía de entrelazamiento de phi_p:',np.round(E_phi_p,3))
print('Entropía de entrelazamiento de phi_m:',np.round(E_phi_m,3))
print('Entropía de entrelazamiento de psi:',np.round(E_psi,3))

Entropía de entrelazamiento de phi_p: 1.0
Entropía de entrelazamiento de phi_m: 1.0
Entropía de entrelazamiento de psi: -0.0


**II.3** Hallar la descomposición de Schmidt de los estados anteriores.

In [ ]:
rhoB_phi_p=rho_phi_p.ptrace(0)
rhoB_phi_m=rho_phi_m.ptrace(0)
rhoB_psi=rho_psi.ptrace(0)

print('Chequeo: los autovalores de rho_A y de rho_B deberían ser iguales.')

sigma2A_phi_p,kA_phi_p = rhoA_phi_p.eigenstates()
sigma2B_phi_p,kB_phi_p = rhoB_phi_p.eigenstates()
print('phi_p:', np.round(sigma2A_phi_p,3), 'y', np.round(sigma2B_phi_p,3))

sigma2A_phi_m,kA_phi_m = rhoA_phi_m.eigenstates()
sigma2B_phi_m,kB_phi_m = rhoB_phi_m.eigenstates()
print('phi_m:', np.round(sigma2A_phi_m,3), 'y', np.round(sigma2B_phi_m,3))

sigma2A_psi,kA_psi = rhoA_psi.eigenstates()
sigma2B_psi,kB_psi = rhoB_psi.eigenstates()
print('psi:', np.round(sigma2A_psi,3), 'y', np.round(sigma2B_psi,3))

print('')
print('Entonces, el número de Schmidt n_s es:')
print('phi_p:', np.count_nonzero(np.round(sigma2A_phi_p,10)))
print('phi_m:', np.count_nonzero(np.round(sigma2A_phi_m,10)))
print('psi:', np.count_nonzero(np.round(sigma2A_psi,10)))

print('')
print('Los valores de sigma_k son:')
print('phi_p:', np.round(np.sqrt(sigma2A_phi_p),3))
print('phi_m:', np.round(np.sqrt(sigma2A_phi_m),3))
print('psi:', np.round(np.sqrt(sigma2A_psi),3))

print('')
print('Y sus correspondientes kets k:')
print('- phi_p')
print('Para el sistema A:')
print(kA_phi_p)
print('y para el sistema B:')
print(kB_phi_p)
print('')
print('- phi_m')
print('Para el sistema A:')
print(kA_phi_m)
print('y para el sistema B:')
print(kB_phi_m)
print('')
print('- psi')
print('Para el sistema A:')
print(kA_psi)
print('y para el sistema B:')
print(kB_psi)

Chequeo: los autovalores de rho_A y de rho_B deberían ser iguales.
phi_p: [0.5 0.5] y [0.5 0.5]
phi_m: [0.5 0.5] y [0.5 0.5]
psi: [0. 1.] y [0. 1.]

Entonces, el número de Schmidt n_s es:
phi_p: 2
phi_m: 2
psi: 1

Los valores de sigma_k son:
phi_p: [0.707 0.707]
phi_m: [0.707 0.707]
psi: [0. 1.]

Y sus correspondientes kets k:
- phi_p
Para el sistema A:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-1.]
 [ 0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]]
y para el sistema B:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-1.]
 [ 0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]]

- phi_m
Para el sistema A:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-1.]
 [ 0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]]
y para el sistema B:
[Quantum object: dims = [[2], [1]], s

In [ ]:
C_phi_p = np.array([[1,0],[0,1]])/np.sqrt(2)
C_phi_m = np.array([[1,0],[0,-1]])/np.sqrt(2)
C_psi = np.array([[1,-1],[1,-1]])/2

U_phi_p,sigma_phi_p,V_phi_p = np.linalg.svd(C_phi_p)
U_phi_m,sigma_phi_m,V_phi_m = np.linalg.svd(C_phi_m)
U_psi,sigma_psi,V_psi = np.linalg.svd(C_psi)

kA_phi_p = qt.Qobj(U_phi_p)*[st0,st1]
kB_phi_p = qt.Qobj(V_phi_p).conj()*[st0,st1]

kA_phi_m = qt.Qobj(U_phi_m)*[st0,st1]
kB_phi_m = qt.Qobj(V_phi_m).conj()*[st0,st1]

kA_psi = qt.Qobj(U_psi)*[st0,st1]
kB_psi = qt.Qobj(V_psi).conj()*[st0,st1]

print('El número de Schmidt n_s es:')
print('phi_p:', np.count_nonzero(np.round(sigma_phi_p,10)))
print('phi_m:', np.count_nonzero(np.round(sigma_phi_m,10)))
print('psi:', np.count_nonzero(np.round(sigma_psi,10)))

print('')
print('Los valores de sigma_k son:')
print('phi_p:', np.round(sigma_phi_p,3))
print('phi_m:', np.round(sigma_phi_m,3))
print('psi:', np.round(sigma_psi,3))

print('')
print('Y sus correspondientes kets k:')
print('- phi_p')
print('Para el sistema A:')
print(kA_phi_p)
print('y para el sistema B:')
print(kB_phi_p)
print('')
print('- phi_m')
print('Para el sistema A:')
print(kA_phi_m)
print('y para el sistema B:')
print(kB_phi_m)
print('')
print('- psi')
print('Para el sistema A:')
print(kA_psi)
print('y para el sistema B:')
print(kB_psi)

El número de Schmidt n_s es:
phi_p: 2
phi_m: 2
psi: 1

Los valores de sigma_k son:
phi_p: [0.707 0.707]
phi_m: [0.707 0.707]
psi: [1. 0.]

Y sus correspondientes kets k:
- phi_p
Para el sistema A:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]]
y para el sistema B:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]]

- phi_m
Para el sistema A:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]]
y para el sistema B:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]]

- psi
Para el sistema 

**II.4** Para $|\alpha|^2+|\beta|^2=1$, hallar la descomposición de Schmidt del estado
$$\ket{\Psi_{AB}}=\alpha\,\frac{\ket{00}+\ket{11}}{\sqrt{2}}+\beta\,\frac{\ket{01}+\ket{10}}{\sqrt{2}}$$
y a partir de ella indicar: a) cuándo el estado será separable, b) cuándo será entrelazado, y c) en qué caso el entrelazamiento será máximo.

In [ ]:
sp.init_printing(use_latex='mathjax')
alpha, beta = sp.symbols('alpha,beta')
C_psi=sp.Matrix([[alpha/sp.sqrt(2),beta/sp.sqrt(2)],[beta/sp.sqrt(2),alpha/sp.sqrt(2)]])
CCd_psi=C_psi * C_psi.H # C * C daga
CdC_psi=C_psi * C_psi.H # C daga * C

CCd_diag = CCd_psi.diagonalize()
CdC_diag = CdC_psi.diagonalize()

U_psi = CCd_diag[0]/sp.sqrt(CCd_diag[0].norm()*CCd_diag[0].inv().norm()) # preguntar si esto vale siempre
V_psi = CdC_diag[0]/sp.sqrt(CdC_diag[0].norm()*CdC_diag[0].inv().norm()) # (relación daga / inversa)

kA_psi = qt.Qobj(np.array(U_psi))*[st0,st1]
kB_psi = qt.Qobj(np.array(V_psi)).conj()*[st0,st1]

avals_psi_U = CCd_diag[1]
avals_psi_V = CdC_diag[1]
print('Chequeo: la resta entre las matrices D^2 tiene que ser nula:', avals_psi_U-avals_psi_V)
print('')
print('Los kets k son:')
print('Para el sistema A:')
print(kA_psi)
print('y para el sistema B:')
print(kB_psi)
print('')
print('Y sus valores de sigma_k^2 son:')
avals_psi_U.get_diag_blocks()

Chequeo: la resta entre las matrices D^2 tiene que ser nula: Matrix([[0, 0], [0, 0]])

Los kets k son:
Para el sistema A:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]]
y para el sistema B:
[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]]

Y sus valores de sigma_k^2 son:


⎡⎡  _     _     _     _⎤  ⎡  _     _     _     _⎤⎤
⎢⎢α⋅α   α⋅β   β⋅α   β⋅β⎥  ⎢α⋅α   α⋅β   β⋅α   β⋅β⎥⎥
⎢⎢─── - ─── - ─── + ───⎥, ⎢─── + ─── + ─── + ───⎥⎥
⎣⎣ 2     2     2     2 ⎦  ⎣ 2     2     2     2 ⎦⎦

**II.5** a) Indicar en qué se diferencian el estado de Bell $\ket{\Psi_{AB}}=\frac{\ket{01}+\ket{10}}{\sqrt{2}}$ y el estado descripto por el operador densidad
$$\rho_{AB}=\frac{1}{2}\left(\ket{01}\bra{01}+\ket{10}\bra{10}\right)$$
b) Indicar si es posible distinguirlos mediante

i) el valor medio de un observable local $O_A\otimes I_B$.

ii) el valor medio de un observable $O=O_A\otimes O_B$

In [ ]:
chi_AB = qt.ket2dm((st01+st10)/np.sqrt(2))
chi_AB

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.  0. ]]

In [ ]:
rho_AB = (st01*st01.dag()+st10*st10.dag())/2
rho_A = rho_AB.ptrace(1)
chi_A = chi_AB.ptrace(1)
print('La resta entre sus densidades locales es:')
rho_A-chi_A

La resta entre sus densidades locales es:


Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [ ]:
O_AB = qt.tensor(qt.sigmax(),qt.sigmax())
res_rho = (rho_AB*O_AB).tr()
res_chi = (chi_AB*O_AB).tr()
print('Resultado con rho: ',res_rho)
print('Resultado con chi: ',res_chi)

Resultado con rho:  0.0
Resultado con chi:  0.9999999999999998
